trigger:
- '*'

pool:
  vmImage: 'ubuntu-latest'

steps:
  - checkout: self

  - task: DockerInstaller@0
    displayName: Docker Install
    inputs:
      dockerVersion: '17.09.0-ce'

  - task: Docker@2
    displayName: Docker Build/Publish
    inputs:
      command: 'buildAndPush'
      containerRegistry: $(ACR-SERVICE-CONNECTION)
      repository: $(ACR-REPOSITORY-NAME)
      tags: $(Build.SourceBranchName)
      Dockerfile: '**/Dockerfile'
